---
title: Defremont
timezone: "America/Belem"
url: http://defremont.github.io
baseurl:
description: "André Defrémont, 1993, Belém do Pará, Bachelor of Information Systems from the Federal University of Pará (UFPA) with skills that promote the user experience (UX / UI) of web projects through the best tools and always seeking the value proposition design."
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  products:
    title: Products
    output: true
disqus: "defremont"
google_analytics: "UA-26063629-2"
fb_app_id: "1153473038113359"
# Sass/SCSS settings
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    comments: true
    social-share: true
- scope:
    path: ''
  values:
    layout: page
    show-avatar: true
- scope:
    type: products
  values:
    layout: product
    show-avatar: false
navbar-links:
  About/Contact: aboutme
  Portfolio:
  - APP: https://app.amachains.io/
  - MARKETPLACE: https://marketplace.amachains.io/
  - TRACK: https://track.amachains.io/1620249060120
  - DASP: http://defremont.github.io/files/DASP.pdf
  - DEVFINDER: https://romantic-dijkstra-654317.netlify.app/
avatar: "/img/avatar-icon.png"
author:
  name: André Defrémont
  email: andre.def93@gmail.com
  facebook: andre.defremont
  github: Defremont
  gitlab: Defremont
  twitter: andredefremont
  reddit: defremont
  google-plus: "+andredefremont"
  linkedin: andredefremont
  whatsapp: "+55091981348438"
  stackoverflow: yourlink
  snapchat: defremont
  instagram: defremont
  youtube: yourlink
  spotify: yourname
  telephone: "+55 091 981348438"


footer-links-active:
  rss: false
  facebook: true
  email: true
  twitter: true
  google-plus: false
  github: true
  gitlab: true
  reddit: true
  linkedin: true
  whatsapp: true
  stackoverflow: false
  snapchat: false
  instagram: true
  youtube: false
  spotify: false
  telephone: true
share-links-active:
  twitter: true
  facebook: true
  google: false
  linkedin: true
url-pretty: defremont.github.io
excerpt_length: 50
title-separator: "-"
markdown: kramdown
highlighter: rouge
permalink: "/:year-:month-:day-:title/"
paginate: 5
markdown: kramdown
link-tags: false
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
- Vagrantfile
prose:
  rooturl: _posts
  media: img
  ignore:
  - 404.html
  - LICENSE
  - feed.xml
  - _config.yml
  - "/_layouts"
  - "/_includes"
  - "/css"
  - "/img"
  - "/js"
  metadata:
    _posts:
    - name: layout
      field:
        element: hidden
        value: post
    - name: title
      field:
        element: text
        label: Post title
        placeholder: Title
        alterable: true
    - name: subtitle
      field:
        element: textarea
        label: Subtitle
        placeholder: A description of your post.
        alterable: true
    - name: date
      field:
        element: text
        label: Date
        help: Enter date of post.
        placeholder: yyyy-mm-dd
        alterable: true
    - name: image
      field:
        element: text
        label: Image
        help: Add a thumbnail image to your post.
        placeholder: Thumbnail
        alterable: true
    - name: published
      field:
        element: checkbox
        label: Publish
        help: Check to publish post, uncheck to hide.
gems:
- jekyll-paginate
- jekyll-admin
- jekyll-sitemap
- jekyll-seo-tag

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
