---
title: André Defrémont
timezone: America/Sao_Paulo
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    comments: true
    social-share: true
- scope:
    path: ''
  values:
    layout: page
    show-avatar: true
url: http://defremont.github.io
baseurl: 
description: Consultor de Projetos Web
navbar-links:
  Sobre: aboutme
  Exemplos de Projetos:
  - Site Pessoal 1: https://defremont.github.io/portfolio/
  - Site Pessoal 2: https://defremont.github.io/portfolio2/
  - Blog Pessoal: https://defremont.github.io/blog
  - Site Institucional 1: https://defremont.github.io/exemplo/
  - Site Institucional 2: https://castledevup.github.io/siteimagem/
  - Castle Dev: https://castledevup.github.io
avatar: "/img/avatar-icon.png"
author:
  name: André Defrémont
  email: andre.def93@gmail.com
  facebook: andre.defremont
  github: Defremont
  twitter: andredefremont
  reddit: defremont
  google-plus: "+yourname"
  linkedin: yourname
  xing: yourname
  stackoverflow: yourlink
  snapchat: defremont
  instagram: defremont
  youtube: yourlink
  spotify: yourname
  telephone: "+55 091 981348438"
footer-links-active:
  rss: false
  facebook: true
  email: true
  twitter: true
  google-plus: false
  github: true
  reddit: true
  linkedin: false
  xing: false
  stackoverflow: false
  snapchat: false
  instagram: true
  youtube: false
  spotify: false
  telephone: true
share-links-active:
  twitter: true
  facebook: true
  google: false
  linkedin: true
url-pretty: defremont.github.io
excerpt_length: 50
title-separator: "-"
markdown: kramdown
highlighter: rouge
permalink: "/:year-:month-:day-:title/"
paginate: 5
kramdown:
  input: GFM
link-tags: false
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
- Vagrantfile
prose:
  rooturl: _posts
  media: img
  ignore:
  - 404.html
  - LICENSE
  - feed.xml
  - _config.yml
  - "/_layouts"
  - "/_includes"
  - "/css"
  - "/img"
  - "/js"
  metadata:
    _posts:
    - name: layout
      field:
        element: hidden
        value: post
    - name: title
      field:
        element: text
        label: Post title
        placeholder: Title
        alterable: true
    - name: subtitle
      field:
        element: textarea
        label: Subtitle
        placeholder: A description of your post.
        alterable: true
    - name: date
      field:
        element: text
        label: Date
        help: Enter date of post.
        placeholder: yyyy-mm-dd
        alterable: true
    - name: image
      field:
        element: text
        label: Image
        help: Add a thumbnail image to your post.
        placeholder: Thumbnail
        alterable: true
    - name: published
      field:
        element: checkbox
        label: Publish
        help: Check to publish post, uncheck to hide.
gems:
- jekyll-paginate
- jekyll-admin
